1.GO TO START:
--	SQL
--		MICROSOFT SQL SERVER MANAGEMENT STUDIO
--		<SSMS>

2.CONNECT TO LOCAL SERVER

3. TWO WINDOWS ARE THERE IN SQL:
	1.EDITOR WINDOW
	2.OBJECT EXPLORER
	3.NEW QUERY
		NEW WINDOW(QUERY WINDOW)
		<SAVE> THREE OPTIONS:
		1.SAVE
		2.SAVE ALL
		3.SAVE AS(INITIALLY)

4.DATABASE:
	<EXPAND>
	1.DATABASES
	2.SECURITY
	3.SERVER OBJECTS
	4.REPLICATION
	5.POLYBASE
	6.ALWAYS ON HIGH AVAILIBILITY
	7.MANAGEMENT
	8.INTEGRATION SERVICES CATALOGS
	9.SQL SERVER AGENT
	10.XEVENT PROFILER

5.DATABASE:
	DATABASE IS A COLLECTION
		1.TABLES
		2.VIEW
		3.STORE PROCEDURE
		4.FUNCTIONS ETC...

6.HOW TO START PROGRAMMING IN SQL?
ANS: CREATE DATABASE

7.HOW TO CREATE DATABASE?
ANS:
	CREATE DATABASE DV_202402;

HOW TO USE DATABASE?
ANS:
USE DV_202402;

HOW TO DROP DATABASE?
DROP DATABASE DV_202402;
Cannot drop database "DV_202402" because it is currently in use.
DROP DATABASE DV_202402;
PERMENTANTLY REMOVED:

CREATE DATABASE DV_202402;
USE DATABASENAME: SYNTAX
USE DV_202402;

DEFAULT DATABASE: MASTER
USERDEFINED DATABASE

1.NAMING CRITERIA MUST BE FOLLOWED:
TEST:
DV 202402:NO (SPACE)
DV.202402: NO(DOT)
DV@202402: YES(@,#,$)
DV_202402: YES

8. WHEN WE CREATE A DATABASE, WE SEE DEFAULT OBJECTS:
	1.DATABASE DIAGRAMS
	2.TABLES
	3.VIEWS
	4.EXTERNAL RESOURCES
	5.SYNONYMS
	6.PROGRAMMABILITY
	7.SERVICE BROKER
	8.STORAGE
	9.SECURITY

BEING A DATA SCIENTIST WE NEED TO FOCUS ON THREE THINGS:
	1.TABLES
	2.VIEWS
	3.PROGRAMMABILITY

9.WHY SQL?
ANS:
1.DATA STORES FROM OLTP(ONLINE TRANSACTIONAL PROCESS) IN THE BACKEND 
DATABASE (SQL SERVER, ORACLE, TERADATA, DB2) STORES YOUR DATA.
2.SQL PROGRAMMING HELPS US TO DO ANALYSIS WITH DATA IN DATABASE(INTERFACE)
3.CLEAN AND MANIPULATE DATA

HOW TO CREATE DATABASE? KEYWORD: CREATE DATABASE
USE DATABASE ?: USE
DROP DATABASE?: DROP DATABASE

10. SQL QUERY?
EG1: I AM HAVING BOOKS MATHEMATICS, FICTION, DATASCIENCE, LANGUAGE IN A SHELF.
TAKE A BOOK ON DATASCIENCE

SELECT
DATASCIENCE
FROM SHELF;

EG2: THERE IS A TABLE MED_2024: COMPANY, CUSTOMER_ID, AGE, GENDER, STATE_CODE, TOWN, SPENT_AMOUNT
ANALYSIS CUSTOMER_ID, COMPANY, AGE, GENDER, SPENT_AMOUNT.

SELECT
CUSTOMER_ID,
COMPANY,
AGE,
GENDER,
SPENT_AMOUNT
FROM MED_2024;

SELECT
CUSTOMER_ID, COMPANY, AGE, GENDER, SPENT_AMOUNT
FROM MED_2024;

select
customer_id,company,age,gender,spent_amount
from med_2024;

11. SQL TABLE:

COLUMNS: IN SQL ITS CALLED AS FIELD( STU_ID,STU_NAME, AGE, GENDER, EDUCATION, DOE, COURSE)
ROWS:IN SQL ITS CALLED AS RECORDS(S1	AHUTI	26	FEMALE	BTECH	01-12-2024	MPAA)

CREATE TABLE STU_ENQ_2024
(STU_ID CHAR(10),
STU_NAME CHAR(50),
AGE INT,
GENDER CHAR(10),
EDUCATION CHAR(15),
DOE DATE,
COURSE CHAR(10)
);

Commands completed successfully.

HOW TO SEE THE TABLE?
ANS:
SELECT * FROM STU_ENQ_2024;

HOW TO INSERT VALUES INTO TABLE?

INSERT INTO STU_ENQ_2024 VALUES('S1','AHUTI',26,'FEMALE','BTECH','01-12-2024','MPAA');
(1 row affected)

SELECT * FROM STU_ENQ_2024;

INSERT INTO STU_ENQ_2024 VALUES('S2','ALISHA',28,'FEMALE','MBA','01-14-2024','MPIDS');
INSERT INTO STU_ENQ_2024 VALUES('S3','ANKIT',27,'MALE','MCOM','02-10-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S4','ASHOK',30,'MALE','MTECH','02-22-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S5','ROHIT',29,'MALE','BTECH','02-20-2024','MPIDS');

SELECT * FROM STU_ENQ_2024;

HOW TO DROP TABLE?
ANS:
DROP TABLE STU_ENQ_2024;

SELECT * FROM STU_ENQ_2024;
Invalid object name 'STU_ENQ_2024'.

DROP TABLE PERMENTANTLY REMOVES TABLE FROM DATA BASE.

CREATE TABLE STU_ENQ_2024
(STU_ID CHAR(10),
STU_NAME CHAR(50),
AGE INT,
GENDER CHAR(10),
EDUCATION CHAR(15),
DOE DATE,
COURSE CHAR(10)
);

INSERT INTO STU_ENQ_2024 VALUES('S1','AHUTI',26,'FEMALE','BTECH','01-12-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S2','ALISHA',28,'FEMALE','MBA','01-14-2024','MPIDS');
INSERT INTO STU_ENQ_2024 VALUES('S3','ANKIT',27,'MALE','MCOM','02-10-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S4','ASHOK',30,'MALE','MTECH','02-22-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S5','ROHIT',29,'MALE','BTECH','02-20-2024','MPIDS');

SELECT * FROM STU_ENQ_2024;

HOW TO DELETE TABLE?
ANS:
DELETE STU_ENQ_2024;

SELECT * FROM STU_ENQ_2024;

DELETE COMMAND REMOVES THE RECORDS BUT THE TABLE REMAINS.

INSERT INTO STU_ENQ_2024 VALUES('S1','AHUTI',26,'FEMALE','BTECH','01-12-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S2','ALISHA',28,'FEMALE','MBA','01-14-2024','MPIDS');
INSERT INTO STU_ENQ_2024 VALUES('S3','ANKIT',27,'MALE','MCOM','02-10-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S4','ASHOK',30,'MALE','MTECH','02-22-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S5','ROHIT',29,'MALE','BTECH','02-20-2024','MPIDS');

SELECT * FROM STU_ENQ_2024;

DELETE STU_ENQ_2024
WHERE GENDER='FEMALE';
(2 rows affected)

SELECT * FROM STU_ENQ_2024;

DELETE:
	1.DELETE RECORDS
	2. DELETE RECORDS BASED ON CRITERIA

HOW TO TRUNCATE TABLE?
ANS:
TRUNCATE TABLE STU_ENQ_2024;

SELECT * FROM STU_ENQ_2024;
TRUNCATE REMOVES THE RECORDS BUT THE TABLE REMAINS:

WHAT IS THE DIFFERENCE BETWEEN DROP, DELETE, TRUNACATE?
ANS:
DROP:WILL REMOVE THE TABLE COMPLETELY FROM THE DATABASE
DELETE: WILL DELETE THE RECORDS, OR DELETE RECORDS BASED ON CRITERIA HOWEEVER THE TABLE REMAINS
TRUNCATE: DELETE THE RECORDS BUT TABLE REMAINS, TRUNCATE CANNOT DELETE RECORDS BASED ON CONDITIONS

SELECT * FROM STU_ENQ_2024;

INSERT INTO STU_ENQ_2024 VALUES('S1','AHUTI',26,'FEMALE','BTECH','01-12-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S2','ALISHA',28,'FEMALE','MBA','01-14-2024','MPIDS');
INSERT INTO STU_ENQ_2024 VALUES('S3','ANKIT',27,'MALE','MCOM','02-10-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S4','ASHOK',30,'MALE','MTECH','02-22-2024','MPAA');
INSERT INTO STU_ENQ_2024 VALUES('S5','ROHIT',29,'MALE','BTECH','02-20-2024','MPIDS');

12. HOW TO ALTER TABLE?
ANS:
	1.ADD COLUMNS
	2.DELETE COLUMNS
	3.MODIFY

1.ADD COLUMNS

ALTER TABLE STU_ENQ_2024
ADD INSTITUTE CHAR(50),
BATCH CHAR(15);

SELECT * FROM STU_ENQ_2024;

2.DELETE COLUMNS

ALTER TABLE STU_ENQ_2024
DROP COLUMN INSTITUTE, BATCH;

SELECT * FROM STU_ENQ_2024;

3.MODIFY

SELECT * FROM STU_ENQ_2024;

13. DEFAULT OBJECTS:
	1.COLUMNS
	2.KEYS
	3.CONSTRAINTS
	4.TRIGERRS
	5.INDEXES
	6.STATICTICS

14. CONSTRAINTS: 
	CONSTRAINTS ARE USED TO SPECIFY RULES, FOR DATA IN TABLE.
	1.NULL
	2.NOT NULL
	3.UNIQUE
	4.PRIMARY
	5.FOREIGN
	6.CHECK
	7.DEFAULT

1.NULL: DEFAULT

CREATE TABLE STU_ENQ_V1
	(STU_ID CHAR(10),
	STU_NAME CHAR(30),
	AGE INT,
	GENDER CHAR(10),
	EDUCATION VARCHAR(15),
	DOE DATE,
	COURSE CHAR(10)
	);

2.NOT NULL

CREATE TABLE STU_ENQ_V2
	(STU_ID CHAR(10) NOT NULL,
	STU_NAME CHAR(30) NOT NULL,
	AGE INT,
	GENDER CHAR(10) NOT NULL,
	EDUCATION VARCHAR(15) NOT NULL,
	DOE DATE NOT NULL,
	COURSE CHAR(10) NOT NULL
	);

3.UNIQUE:ENSURES THAT ALL VALUES ARE UNIQUE BUT I CAN HAVE ONE NULL VAUE

CREATE TABLE STU_ENQ_V3
	(STU_ID CHAR(10) UNIQUE,
	STU_NAME CHAR(30) NOT NULL,
	AGE INT,
	GENDER CHAR(10) NOT NULL,
	EDUCATION VARCHAR(15) NOT NULL,
	DOE DATE NOT NULL,
	COURSE CHAR(10) NOT NULL
	);

4.PRIMARY KEY

CREATE TABLE STU_ENQ_V4
	(STU_ID CHAR(10) PRIMARY KEY,
	STU_NAME CHAR(30) NOT NULL,
	AGE INT,
	GENDER CHAR(10) NOT NULL,
	EDUCATION VARCHAR(15) NOT NULL,
	DOE DATE NOT NULL,
	COURSE CHAR(10) NOT NULL
	);

DIFFERENCE BETWEEN PRIMARY KEY AND UNIQUE:

PRIMARY KEY:UNIQUE IN NATURE
			CANNOT HAVE NULL VALUE

UNIQUE KEY: UNIQUE IN NATURE
			CAN HAVE NULL VALUES, ONE NULL VALUE

TEST: 
ST_ID1: S1,S2,S3,S4,S5,S6,S7,S8,S9,S10 PRIMARY KEY
STU_ID2: S1,S2,S3, ,S5,S6,S7,S8,S9,S10 UNIQUE KEY

Q1.CAN WE ADD MULTIPLE PRIMARY KEY IN A TABLE?
ANS:NO

CREATE TABLE STU_ENQ_V5
	(STU_ID CHAR(10) PRIMARY KEY,
	STU_NAME CHAR(30) PRIMARY KEY,
	AGE INT,
	GENDER CHAR(10) NOT NULL,
	EDUCATION VARCHAR(15) NOT NULL,
	DOE DATE NOT NULL,
	COURSE CHAR(10) NOT NULL
	);

Cannot add multiple PRIMARY KEY constraints to table 'STU_ENQ_V5'.

Q2. CAN WE GO FOR MULTIPLE UNIQUE KEYS?
ANS:YES

CREATE TABLE STU_ENQ_V6
	(STU_ID CHAR(10) UNIQUE,
	STU_NAME CHAR(30) UNIQUE,
	AGE INT,
	GENDER CHAR(10) NOT NULL,
	EDUCATION VARCHAR(15) NOT NULL,
	DOE DATE NOT NULL,
	COURSE CHAR(10) NOT NULL
	);

Commands completed successfully.

Q3. CAN WE HAVE PRIMARY KEY + UNIQUE KEY IN ATBLE?
ANS:

CREATE TABLE STU_ENQ_V7
	(STU_ID CHAR(10) PRIMARY KEY,
	STU_NAME CHAR(30) UNIQUE,
	AGE INT,
	GENDER CHAR(10) NOT NULL,
	EDUCATION VARCHAR(15) NOT NULL,
	DOE DATE NOT NULL,
	COURSE CHAR(10) NOT NULL
	);

Commands completed successfully.

Q4.CAN WE ADD CONSTARINTS(PRIMARY OR UNIQUE)
ANS:YES

CREATE TABLE STU_ENQ_V8
	(STU_ID CHAR(10) NOT NULL,
	STU_NAME CHAR(30) NOT NULL,
	AGE INT,
	GENDER CHAR(10) NOT NULL,
	EDUCATION VARCHAR(15) NOT NULL,
	DOE DATE NOT NULL,
	COURSE CHAR(10) NOT NULL
	);

ALTER TABLE STU_ENQ_V8
ADD CONSTRAINT ABC PRIMARY KEY(STU_ID);

Q5.CAN WE DROP A PRIMARY KEY?
ANS:YES

ALTER TABLE STU_ENQ_V8
DROP CONSTRAINT ABC;

Q6. CAN WE ADD CONSTRAINT AS UNIQUE KEY?
ANS:

ALTER TABLE STU_ENQ_V8
ADD CONSTRAINT ABC UNIQUE(STU_ID);

Q7.CAN WE DROP A CONSTRAINT UNIQUE?
ANS:YES

ALTER TABLE STU_ENQ_V8
DROP CONSTRAINT ABC;

PRIMARY+UNIQUE= YES
UNIQUE+UNIQUE=YES
PRIMARY+PRIMARY=NO

5.ADDING FOREIGN KEY(REFERENCE KEY)

CUSTOMER_TABLE:(DIMENSION_TABLE)
CUSTOMER_ID,(UNIQUE)
CUSTOMER_NAME,
AGE,
GENDER,
LOCATION,
MOBILE

CREATE TABLE CUSTOMER_MASTER
	(
	CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(30),
	AGE INT,
	GENDER CHAR(10),
	LOCATION VARCHAR(20),
	MOBILE INT
	);

SALES_TABLE:(TRANSACTION TABLE)
ORDER_ID,
ORDER_DATE,
CUSTOMER_ID,(DUPLICATE FIELD): FOREIGN KEY
PRODUCT_NAME,
PRICE,
UNITS,
SALES

CREATE TABLE SALES_MASTERS
	(ORDER_ID INT,
	ORDER_DATE DATE,
	CUSTOMER_ID VARCHAR(20),
	PRODUCT_NAME VARCHAR(30),
	PRICE INT,
	UNITS INT,
	SALES INT
	FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_MASTER(CUSTOMER_ID)
	);

JOIN SALES_TABLE TO CUSTOMER_TABLES WITH CUSTOMER_ID


DIFFERENCE BETWEEN PRIMARY KEY AND FOREIGN KEY:

PRIMARY KEY: IT IS UNIQUE
			DOES NOT CONTAIN ANY NULL VALUE

FOREIGN KEY: IT IS UNIQUE OR DUPLICATE
			CAN CONTAIN NULL VALUES

6.ADDING DEFAULT CONSTARINT:

CREATE TABLE DATASCIENCE_BATCH
	(STU_NAME CHAR(30),
	GENDER VARCHAR(20),
	AGE INT,
	INSTITUTE VARCHAR(30) DEFAULT 'DV ANALYTICS');

SELECT * FROM DATASCIENCE_BATCH;

INSERT INTO DATASCIENCE_BATCH (STU_NAME,GENDER,AGE) VALUES ('LAKSHMI','FEMALE',35);

SELECT * FROM  DATASCIENCE_BATCH;

7.ADDING A CONSTARINT CALL CHECK:

CREATE TABLE STUDENT_GRADE
	(STU_ID INT PRIMARY KEY,
	STU_FNAME VARCHAR(30),
	STU_LNAME VARCHAR(30),
	AGE INT,
	GRADE CHAR(1),
	CONSTRAINT CHK_AGE CHECK(AGE>=23),
	CONSTRAINT CHK_GRADE CHECK(GRADE IN ('A','B','C','D','F'))
	);

INSERT INTO STUDENT_GRADE (STU_ID,STU_FNAME,STU_LNAME,AGE,GRADE) VALUES(1,'ARPITA','TANDI',25,'A');

SELECT * FROM STUDENT_GRADE;

INSERT INTO STUDENT_GRADE (STU_ID,STU_FNAME,STU_LNAME,AGE,GRADE) VALUES(1,'MALINI','PATEL',10,'B');
Violation of PRIMARY KEY constraint 'PK__STUDENT___C97EC9648BCCD9A1'. 
Cannot insert duplicate key in object 'dbo.STUDENT_GRADE'. The duplicate key value is (1).
The statement has been terminated.

INSERT INTO STUDENT_GRADE (STU_ID,STU_FNAME,STU_LNAME,AGE,GRADE) VALUES(5,'MALINI','PATEL',10,'D');

--The INSERT statement conflicted with the CHECK constraint "CHK_AGE". 
--The conflict occurred in database "DV_202402", table "dbo.STUDENT_

--INSERT INTO STUDENT_GRADE (STU_ID,STU_FNAME,STU_LNAME,AGE,GRADE) VALUES (5,'MALINI','PATEL',30,'D');

--INSERT INTO STUDENT_GRADE (STU_ID,STU_FNAME,STU_LNAME,AGE,GRADE) VALUES (6,'MALINI','PATEL',30,'E');

--The INSERT statement conflicted with the CHECK constraint "CHK_GRADE". 
--The conflict occurred in database "DV_202402", table "dbo.S

IMPORT AND EXPORT DATA INTO SQL SERVER:

SELECT * FROM MED_2024;

1. IMPORT THE DATA FROM EXCEL FILE:
STEP 1: SELECT DATABASE-RIGHT CLICK-TASKS-IMPORT DATA
STEP 2: SELECT DATA SOURCE AS EXCEL FILE(TXT FILE,CSV)-BROWSE
STEP 3: SELECT DESTINATION <SQL SERVER OLEDB PROVIDER>
STEP 4: SELECT COPY-RUN-FINISH

2.IMPORT FLAT FILE(.TXT, .CSV )

SELECT * FROM MED_DV_2024_TXT;
SELECT * FROM MED_2024_CSV;

EXPORT DATA FROM SQL SERVER:

STEP1:SELECT DATABASE-RIGHT CLICK-TASKS-EXPORT DATA
STEP2: SELECT DATA SOURCE(SQL SERVER)
STEP3: SELECT DESTINATION-SELECT FILE TYPE(.XLSX,.TXT.CSV)
STEP4: COPY-RUN-FINISH

REVISION: SESSIO 1

1.WHEN WE OPEN SQL SERVER WE SEE TWO WINDOWS:
	1.EDITOR WINDOW
	2.OBJECT EXPLORER
	3.QUERY EDITOR(NEW QUWRY)
		RUN QUERY
	4.MESSAGE WINDOW( PROCESSING TIME, ROWS AFFECTED OR ERROR MESSAGE)
	5.RESULT WINDOW: DISPLAY QUERY OUTPUT
	6.TASK BAR
		1.PROGRAM RUN SUCCESSFULLY
		2.SERVER DETAILS
		3.SERVER PATH
		4.DATABASE(CURRENTLY USE)
		5.PROCESSING TIME
		6.# OF ROWS AFFECTED

2.HOW TO DESCRIBE DATABASE?
ANS:
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
	1.ALL TABLES IN THE DATABASE
	2.ALONG WITH COLUMNS, DATA TYPES OF COLUMNS
	3.COLUMN POSITION

3.HOW TO DESCRIBE THE TABLES IN HE DATABASE?
ANS:
SELECT * FROM INFORMATION_SCHEMA.TABLES;

4.HOW TO DESCIBE A TABLE?
ANS:
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MED_2024';

5.HOW TO SELECT THE ENTIRE TABLE?
ANS:
SELECT * FROM MED_2024;

6.HOW TO SEE THE NUMBER OF RECORDS IN A TABLE?
ANS:
SELECT COUNT(*) FROM MED_2024;

7.HOW TO GET THE NUMBER OF COLUMNS IN A TABLE?
ANS:

SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MED_2024';

8.HOW TO SEE THE FIRST 100 RECORDS FROM A TABLE?
ANS:
SELECT TOP 100* FROM MED_2024;

9.HOW TO SELECT TOP 30 % OF RECORDS FROM TABLE?
ANS:
SELECT TOP 30 PERCENT * FROM MED_2024;

10.HOW TO SELECT RANDOM 100 RECORDS?
ANS:
SELECT TOP 100* FROM MED_2024 ORDER BY NEWID();

11.HOW TO CREATE NEW TABLE FROM EXISTING TABLE?
ANS:
SELECT * INTO MED_NEW_2024 FROM MED_2024;
SELECT * FROM MED_NEW_2024;

12.HOW TO SELECT FIELDS FROM THE TABLE?
ANS:
SELECT
CUSTOMER_ID,
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
SPENT AMOUNT
FROM MED_2024;

Invalid column name 'SPENT'.

SELECT
CUSTOMER_ID,
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
[SPENT AMOUNT]
FROM MED_2024;

SELECT
CUSTOMER_ID,
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
SPENT_AMOUNT
FROM MED_2024;

13.HOW TO USE ALIAS TO A COLUMN NAME?

SELECT
CUSTOMER_ID AS SUBS,
COMPANY AS BUSINESS,
GENDER AS SEX,
AGE,
STATE_CODE AS PROVINCE,
TOWN AS CITY,
SPENT_AMOUNT AS SPENT
FROM MED_2024;

14.HOW TO SEE DISTINCT RECORDS IN A TBLE?
ANS:
SELECT COMPANY FROM MED_2024;
SELECT DISTINCT COMPANY FROM MED_2024;

SELECT COUNT(DISTINCT COMPANY) AS UNQ_VALUES FROM MED_2024;